# exercice 1 :

In [1]:
nl=[]
for x in range(2000, 3000):
    if (x%7==0) and (x%5==0):
        nl.append(str(x))
print (','.join(nl))


2030,2065,2100,2135,2170,2205,2240,2275,2310,2345,2380,2415,2450,2485,2520,2555,2590,2625,2660,2695,2730,2765,2800,2835,2870,2905,2940,2975


# exercice 2 :

In [2]:
n = int(input())
def shortFact(x): return 1 if x <= 1 else x*shortFact(x-1)
print(shortFact(n))

8
40320


# exercice 3 :

In [4]:
n=int(input())
d=dict()
for i in range(1,n+1):
    d[i]=i*i

print(d)

8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


# exercice 4 :

In [5]:
from math import *
C,H = 50,30

def calc(D):
    return sqrt((2*C*D)/H)
    
print(",".join([str(int(calc(int(i)))) for i in input().split(',')]))

150
22


# exercice 5 :

In [14]:
def remove_char(str, n):
      first_part = str[:n] 
      last_part = str[n+1:]
      return first_part + last_part
print(remove_char('kitten', 1))
print(remove_char('kitten', 0))
print(remove_char('kitten', 4))

ktten
itten
kittn


# exercice 6 :

In [8]:
text = "g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle grgl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj."

table = str.maketrans("abcdefghijklmnopqrstuvwxyz", "cdefghijklmnopqrstuvwxyzab")
result = text.translate(table)

print(result)

i hope you didnt translate it by hand. thats what computers are for. doing itin by hand is inefficient and that's why this text is so long. using string.maketrans() is recommended. now apply on the url.


# exercice 7 :

In [9]:
import numpy as np
x= np.arange(6).reshape(3, 2)
print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())

Original array elements:
[[0 1]
 [2 3]
 [4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]


# exercice 8 :

In [10]:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))



Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]
